/**
 * Dataset changelog: one section per published revision (data_hash) with count deltas and the
 * canonical ids added or removed since the previous entry. The id lists come from
 * data/generated/revision-index.json, which this script maintains; the scientific reasons come
 * from the pass logs and are written by hand into the "Notes" line of each section.
 *
 *   pnpm changelog            # append a section if the current build's data_hash is new
 *   pnpm changelog --note "…" # same, with the notes line filled in
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..", "..");
const graphFile = join(root, "apps", "web", "generated", "graph.json");
const indexFile = join(root, "data", "generated", "revision-index.json");
const logFile = join(root, "docs", "dataset-changelog.md");

type Entry = { data_hash: string; generated_at: string; source_commit: string | null; version: string; counts: Record<string, number>; ids: Record<string, string[]> };

const noteArg = process.argv.indexOf("--note");
const note = noteArg > 0 ? process.argv[noteArg + 1] : "";

const g = JSON.parse(readFileSync(graphFile, "utf8"));
const numeric = Object.fromEntries(Object.entries(g.meta.counts).filter(([, v]) => typeof v === "number")) as Record<string, number>;
const current: Entry = {
  data_hash: g.meta.data_hash,
  generated_at: g.meta.built_at,
  source_commit: g.meta.source_commit,
  version: g.meta.version,
  counts: numeric,
  ids: {
    entities: g.entities.map((e: { id: string }) => e.id).sort(),
    claims: g.claims.map((c: { id: string }) => c.id).sort(),
    sources: g.sources.map((s: { id: string }) => s.id).sort(),
    pathways: g.pathways.map((p: { id: string }) => p.id).sort(),
  },
};

const index: Entry[] = existsSync(indexFile) ? JSON.parse(readFileSync(indexFile, "utf8")) : [];
const prev = index[index.length - 1];
if (prev && prev.data_hash === current.data_hash) {
  console.log(`changelog: revision ${current.data_hash} already recorded`);
  process.exit(0);
}

const diff = (a: string[] = [], b: string[]) => ({ added: b.filter((x) => !a.includes(x)), removed: a.filter((x) => !b.includes(x)) });
const lines: string[] = [];
lines.push(`## r${current.data_hash}`, "");
lines.push(`- generated_at: ${current.generated_at}`);
lines.push(`- source_commit: ${current.source_commit ?? "null"}`);
lines.push(`- export format: v${current.version}`);
lines.push(`- supersedes: ${prev ? `r${prev.data_hash}` : "— (first recorded revision)"}`);
const keys = ["entities", "phenomena", "claims", "sources", "pathways_named", "paths_examined", "paths_demonstrated", "matrix_cells", "matrix_cells_empty"];
lines.push(
  `- counts: ${keys.map((k) => `${k} ${current.counts[k]}${prev && prev.counts[k] !== current.counts[k] ? ` (${current.counts[k] - prev.counts[k] > 0 ? "+" : ""}${current.counts[k] - prev.counts[k]})` : ""}`).join(" · ")}`,
);
for (const kind of ["entities", "claims", "sources", "pathways"] as const) {
  if (!prev) break; // the first recorded revision lists counts only; every id is in the exports
  const d = diff(prev.ids[kind], current.ids[kind]);
  if (d.added.length) lines.push(`- ${kind} added (${d.added.length}): ${d.added.join(", ")}`);
  if (d.removed.length) lines.push(`- ${kind} removed (${d.removed.length}): ${d.removed.join(", ")}`);
  if (prev && !d.added.length && !d.removed.length) lines.push(`- ${kind}: no ids added or removed (edits in place are visible in git history of data/canonical)`);
}
lines.push(`- notes: ${note || "(fill in from the pass log: what changed scientifically and why)"}`, "");

const header = existsSync(logFile)
  ? readFileSync(logFile, "utf8")
  : "# Dataset changelog\n\nOne section per published revision, newest first. A revision is a `data_hash` (see docs/data-api.md § Revisions). Generated by `pnpm changelog`; the notes line is written by hand.\n\n";
const [head, ...rest] = header.split(/^(?=## r)/m);
writeFileSync(logFile, head + lines.join("\n") + "\n" + rest.join(""));
index.push(current);
writeFileSync(indexFile, JSON.stringify(index));
console.log(`changelog: recorded r${current.data_hash}${prev ? ` (supersedes r${prev.data_hash})` : ""}`);
