// Loop-3 review mechanics: helpers injected into the ChatGPT tab (via the Claude-in-Chrome javascript tool)
// after every page load. __pta_reply(i) reads assistant turn i from React fiber state (never the DOM, which
// virtualises long replies); __pta_dump(i) swaps the page body for a <pre> so get_page_text can read the
// whole reply, __pta_restore() puts it back; __pta_send(msg) is ASYNC — always await it. A Web Lock keeps
// the tab alive in the background. Source of record for design/LOG.md "loop mechanics".
window.__pta_reply = (i) => { const el=document.querySelectorAll('[data-message-author-role="assistant"]')[i]; if(!el) return null; const key=Object.keys(el).find(k=>k.startsWith('__reactFiber$')); let f=el[key]; let found=null; let d=0; while(f && d<40){ const p=f.memoizedProps; if(p){ for(const k of Object.keys(p)){ const v=p[k]; if(v && typeof v==='object' && v.content && v.content.parts){ found=v; break; } if(v && typeof v==='object' && v.message && v.message.content && v.message.content.parts){ found=v.message; break;} } } if(found) break; f=f.return; d++; } return found ? found.content.parts.join('') : null; };
window.__pta_dump = (i) => { const t=window.__pta_reply(i); if(t==null) return 'no reply '+i; const main=document.querySelector('main'); const old=document.getElementById('__pta_dump'); if(old) old.remove(); const pre=document.createElement('pre'); pre.id='__pta_dump'; pre.textContent='PTA-REPLY-START\n'+t+'\nPTA-REPLY-END'; for (const ch of main.children) { ch.setAttribute('data-pta-hidden', ch.style.display||''); ch.style.display='none'; } main.appendChild(pre); return 'dumped '+t.length; };
window.__pta_restore = () => { const pre=document.getElementById('__pta_dump'); if(pre) pre.remove(); for (const ch of document.querySelectorAll('[data-pta-hidden]')) { ch.style.display=ch.getAttribute('data-pta-hidden'); ch.removeAttribute('data-pta-hidden'); } return 'restored'; };
window.__pta_status = () => { const msgs=document.querySelectorAll('[data-message-author-role="assistant"]'); const t=msgs.length?window.__pta_reply(msgs.length-1):null; return JSON.stringify({n: msgs.length, len: t?t.length:0, stop: !!document.querySelector('button[data-testid="stop-button"]'), url: location.pathname}); };
window.__pta_send = async (msg) => { const ed=document.querySelector('#prompt-textarea'); ed.focus(); document.execCommand('insertText', false, msg); await new Promise(r=>setTimeout(r,400)); const ev=new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true,cancelable:true}); ed.dispatchEvent(ev); await new Promise(r=>setTimeout(r,4000)); return JSON.stringify({userMsgs: document.querySelectorAll('[data-message-author-role="user"]').length, composer: document.querySelector('#prompt-textarea')?.innerText.length, url: location.pathname}); };
if (!window.__pta_lock) { window.__pta_lock = true; navigator.locks.request('pta-keepalive', () => new Promise(() => {})); }
